<?php

namespace App;

use App\Filters\ThreadFilter;
use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
  protected $guarded = [];
  protected $with = ['channel:id,slug,access', 'creator:id,name'];
  protected $appends = ['IsPublished'];

  protected static function boot()
  {
    parent::boot(); // TODO: Change the autogenerated stub

    self::deleting(function ($model) {
       $model->replies->each->delete();
    });
  }

  public function channel()
  {
    return $this->belongsTo(Channel::class, 'channel_id');
  }

  public function creator()
  {
    return $this->belongsTo(User::class, 'user_id');
  }

  public function scopeFilters($query, ThreadFilter $filter)
  {
    return $filter->apply($query);
  }

  public function replies()
  {
    return $this->hasMany(Reply::class);
  }

  public function addReply($reply)
  {
    return $this->replies()->create($reply);
  }

  public function getIsPublishedAttribute()
  {

  }
}
